name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.13.15 # This is the action
        with:
          heroku_api_key: 2e00f265-e8c3-4e42-8936-283e8783e83a
          heroku_app_name: "dunkhead" #Must be unique in Heroku
          heroku_email: "nestrada2@dons.usfca.edu"